#!/bin/bash

# ------------------------------------------------------------------
# Create genome index and genome size files.
#
# In this step, each genome assembly is indexed using samtools faidx.
# The resulting genome index (.fai) is then used to generate genome
# size files required for downstream BEDTools analyses, including
# creating upstream and downstream flanking regions surrounding
# opsin genes.
#
# The same workflow was repeated for each Hydra genome included in
# this study.
# ------------------------------------------------------------------

############################################################
# Hydra vulgaris AEP
############################################################

# Index genome assembly
samtools faidx HVAEP.genome.fa

# Create genome size file for BEDTools
cut -f1,2 HVAEP.genome.fa.fai > HvAEP_genome_info


############################################################
# Hydra oligactis
############################################################

# Index genome assembly
samtools faidx HOLI.genome.fa

# Create genome size file for BEDTools
cut -f1,2 HOLI.genome.fa.fai > hydra_Oli_genome_info


############################################################
# Hydra 105
############################################################

# Index genome assembly
samtools faidx GCF_022113875.1_Hydra_105_v3_genomic.fna

# Create genome size file for BEDTools
cut -f1,2 GCF_022113875.1_Hydra_105_v3_genomic.fna.fai > hydra_105_genome_info


############################################################
# Hydra viridissima
############################################################

# Index genome assembly
samtools faidx GCF_964215635.1_jhHydViri1.1_genomic.fna

# Create genome size file for BEDTools
cut -f1,2 GCF_964215635.1_jhHydViri1.1_genomic.fna.fai > hydra_viri_genome_info


############################################################
# Expected output
############################################################
#
# HvAEP_genome_info
# hydra_Oli_genome_info
# hydra_105_genome_info
# hydra_viri_genome_info
#
# These genome size files are used as input for BEDTools when
# generating upstream and downstream flanking regions around
# opsin genes.
#

echo "Finished creating genome index and genome size files."
